// <auto-generated />
namespace Azure.CognitiveServices.FaceRecognition.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initalcommit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initalcommit));
        
        string IMigrationMetadata.Id
        {
            get { return "201703281608482_inital-commit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
